# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('caption_text', models.TextField(blank=True, null=True, verbose_name='caption text')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='Bild', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'images',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_simpleslider_slider', serialize=False, to='cms.CMSPlugin')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('dots', models.BooleanField(default=False, verbose_name='dots')),
                ('fade', models.BooleanField(default=False, verbose_name='fade')),
                ('autoplay', models.BooleanField(default=True, verbose_name='autoplay')),
                ('image_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmsplugin_simpleslider_image_options', to='filer.ThumbnailOption', verbose_name='image size')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.AddField(
            model_name='image',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cmsplugin_simpleslider.Slider'),
        ),
    ]
